### ISSUE TITLE
5.12.1 import chunk

### ISSUE THREAD

**Issue by h615861768** [airbnb/lottie-web#2992]
Latest version of lottie (5.12.1) breaks imports

5.12.0 worked fine
5.12.1 results in:

error msg:  lottie.loadAnimation is not a function.

i use 
`import('lottie-web').then(lottie => { lottie.loadAnimation(...)})`
can works on 5.12.0

in 5.12.1 
`import('lottie-web').then(lottie => { console.log(lottie)}; `

console.log lottie root is only `default`, need use lottie.default.loadAnimation

**Comment by bodymovin** [comment]
I just published version 5.12.2 that should fix this. Can you let me know if it fixes it?

**Comment by h615861768** [comment]
> 

i try it in local,  5.12.2 is fixed 👍🏻
