### ISSUE TITLE
Lottie-web 5.3.2/3 break our exported files

### ISSUE THREAD

**Issue by RanSlidely** [airbnb/lottie-web#1286]
HI,
we got the new Lottie-web version is we have some issues in our animation.json that not work and we getting an error. 
I try to check the changes you made to see what happen but I don't find any clue.

All is working fine in version 5.3.1 and less.
The animation data JSON are export with older plugin version.
Are some of the errors:|
Uncaught TypeError: Cannot read property 'length' of undefined
    at SVGCompElement.BaseRenderer.buildAllItems (webpack-internal:///65:5709)
    at SVGCompElement.ICompElement.initElement (webpack-internal:///65:8075)
    at new SVGCompElement (webpack-internal:///65:8198)
    at SVGRenderer.createComp (webpack-internal:///65:5846)
    at SVGRenderer.BaseRenderer.createItem (webpack-internal:///65:5689)
    at SVGRenderer.buildItem (webpack-internal:///65:5924)
    at SVGRenderer.BaseRenderer.buildAllItems (webpack-internal:///65:5711)
    at SVGRenderer.BaseRenderer.initItems (webpack-internal:///65:5738)
    at AnimationItem.checkLoaded (webpack-internal:///65:11355)
    at AnimationItem.imagesLoaded (webpack-internal:///65:11302)

Uncaught TypeError: this.elements[i].prepareFrame is not a function
    at SVGRenderer.renderFrame (webpack-internal:///65:5982)
    at AnimationItem.renderFrame (webpack-internal:///65:11389)
    at AnimationItem.gotoFrame (webpack-internal:///65:11382)
    at AnimationItem.checkLoaded (webpack-internal:///65:11360)
    at AnimationItem.completeData (webpack-internal:///65:11336)
    at AnimationItem.waitForFontsLoaded (webpack-internal:///65:11344)

I attache the JSON files.
[send-to-lottie.zip](https://github.com/airbnb/lottie-web/files/2455160/send-to-lottie.zip)

I hope that we don't need to export all files with a new AF plugin version to avoid this error.
Thanks 
Ran

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by RanSlidely** [comment]
There is a way to send it privately?

**Comment by bodymovin** [comment]
Found the issue.
I'll have it fixed later today.

**Comment by RanSlidely** [comment]
Thanks, 👍 Waiting :-)

**Comment by RanSlidely** [comment]
It will be easier for me to test the fixed with release version..
When can you upload a new version?

Thanks

**Comment by RanSlidely** [comment]
I try to pull it using npm but I'm getting 5.3.3 version.

**Comment by bodymovin** [comment]
published
